// This code was generated by net.maritimecloud.common.cqrs.contract.SourceGenerator
// Generated Code is based on the contract defined in net.maritimecloud.identityregistry.command.IdentityRegistryContract
// Please modify the contract instead of this file!
package net.maritimecloud.identityregistry.command.api;

import org.axonframework.commandhandling.annotation.TargetAggregateIdentifier;
import org.axonframework.common.Assert;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import net.maritimecloud.common.cqrs.Command;

/**
 * GENERATED CLASS!
 * @see net.maritimecloud.identityregistry.command.IdentityRegistryContract#SendResetPasswordInstructions
 */
public class SendResetPasswordInstructions implements Command {

    @TargetAggregateIdentifier
    private final String emailAddress;

    @JsonCreator
    public SendResetPasswordInstructions(
            @JsonProperty("emailAddress") String emailAddress
    ) {
        Assert.notNull(emailAddress, "The emailAddress must be provided");
        this.emailAddress = emailAddress;
    }

    public String getEmailAddress() {
        return emailAddress;
    }

}

