// This code was generated by net.maritimecloud.common.cqrs.contract.SourceGenerator
// Generated Code is based on the contract defined in net.maritimecloud.identityregistry.command.IdentityRegistryContract
// Please modify the contract instead of this file!
package net.maritimecloud.identityregistry.command.api;

import org.axonframework.commandhandling.annotation.TargetAggregateIdentifier;
import net.maritimecloud.common.cqrs.contract.Event;
import net.maritimecloud.identityregistry.command.user.UserId;

/**
 * GENERATED CLASS!
 * @see net.maritimecloud.identityregistry.command.IdentityRegistryContract#UserEmailAddressVerified
 */
@Event
public class UserEmailAddressVerified {

    @TargetAggregateIdentifier
    private final UserId userId;
    private final String username;
    private final String emailAddress;

    public UserEmailAddressVerified(
            UserId userId,
            String username,
            String emailAddress
    ) {
        this.userId = userId;
        this.username = username;
        this.emailAddress = emailAddress;
    }

    public UserId getUserId() {
        return userId;
    }

    public String getUsername() {
        return username;
    }

    public String getEmailAddress() {
        return emailAddress;
    }

}

