// This code was generated by net.maritimecloud.common.cqrs.contract.SourceGenerator
// Generated Code is based on the contract defined in net.maritimecloud.identityregistry.command.IdentityRegistryContract
// Please modify the contract instead of this file!
package net.maritimecloud.identityregistry.command.api;

import org.axonframework.commandhandling.annotation.TargetAggregateIdentifier;
import net.maritimecloud.common.cqrs.contract.Event;
import net.maritimecloud.identityregistry.command.user.UserId;

/**
 * GENERATED CLASS!
 * @see net.maritimecloud.identityregistry.command.IdentityRegistryContract#UserRegistered
 */
@Event
public class UserRegistered {

    @TargetAggregateIdentifier
    private final UserId userId;
    private final String prefferedUsername;
    private final String emailAddress;
    private final String obfuscatedPassword;
    private final String emailVerificationCode;

    public UserRegistered(
            UserId userId,
            String prefferedUsername,
            String emailAddress,
            String obfuscatedPassword,
            String emailVerificationCode
    ) {
        this.userId = userId;
        this.prefferedUsername = prefferedUsername;
        this.emailAddress = emailAddress;
        this.obfuscatedPassword = obfuscatedPassword;
        this.emailVerificationCode = emailVerificationCode;
    }

    public UserId getUserId() {
        return userId;
    }

    public String getPrefferedUsername() {
        return prefferedUsername;
    }

    public String getEmailAddress() {
        return emailAddress;
    }

    public String getObfuscatedPassword() {
        return obfuscatedPassword;
    }

    public String getEmailVerificationCode() {
        return emailVerificationCode;
    }

}

