// This code was generated by net.maritimecloud.common.cqrs.contract.SourceGenerator
// Generated Code is based on the contract defined in net.maritimecloud.identityregistry.command.IdentityRegistryContract
// Please modify the contract instead of this file!
package net.maritimecloud.identityregistry.command.api;

import org.axonframework.commandhandling.annotation.TargetAggregateIdentifier;
import org.axonframework.common.Assert;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import net.maritimecloud.common.cqrs.Command;
import net.maritimecloud.identityregistry.command.user.UserId;

/**
 * GENERATED CLASS!
 * @see net.maritimecloud.identityregistry.command.IdentityRegistryContract#VerifyEmailAddress
 */
public class VerifyEmailAddress implements Command {

    @TargetAggregateIdentifier
    private final UserId userId;
    private final String emailAddressVerificationId;

    @JsonCreator
    public VerifyEmailAddress(
            @JsonProperty("userId") UserId userId,
            @JsonProperty("emailAddressVerificationId") String emailAddressVerificationId
    ) {
        Assert.notNull(userId, "The userId must be provided");
        Assert.notNull(emailAddressVerificationId, "The emailAddressVerificationId must be provided");
        this.userId = userId;
        this.emailAddressVerificationId = emailAddressVerificationId;
    }

    public UserId getUserId() {
        return userId;
    }

    public String getEmailAddressVerificationId() {
        return emailAddressVerificationId;
    }

}

