// This code was generated by net.maritimecloud.common.cqrs.contract.SourceGenerator
// Generated Code is based on the contract defined in net.maritimecloud.serviceregistry.command.ServiceRegistryContract
// Please modify the contract instead of this file!
package net.maritimecloud.serviceregistry.command.api;

import org.axonframework.commandhandling.annotation.TargetAggregateIdentifier;
import org.axonframework.common.Assert;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import net.maritimecloud.common.cqrs.Command;
import net.maritimecloud.serviceregistry.command.organization.membership.MembershipId;

/**
 * GENERATED CLASS!
 * @see net.maritimecloud.serviceregistry.command.ServiceRegistryContract#acceptUsersMembershipApplication
 */
public class AcceptUsersMembershipApplication implements Command {

    @TargetAggregateIdentifier
    private final MembershipId membershipId;

    @JsonCreator
    public AcceptUsersMembershipApplication(
            @JsonProperty("membershipId") MembershipId membershipId
    ) {
        Assert.notNull(membershipId, "The membershipId must be provided");
        this.membershipId = membershipId;
    }

    public MembershipId getMembershipId() {
        return membershipId;
    }

}

