// This code was generated by net.maritimecloud.common.cqrs.contract.SourceGenerator
// Generated Code is based on the contract defined in net.maritimecloud.serviceregistry.command.ServiceRegistryContract
// Please modify the contract instead of this file!
package net.maritimecloud.serviceregistry.command.api;

import org.axonframework.commandhandling.annotation.TargetAggregateIdentifier;
import net.maritimecloud.common.cqrs.contract.Event;
import net.maritimecloud.serviceregistry.command.organization.OrganizationId;

/**
 * GENERATED CLASS!
 * @see net.maritimecloud.serviceregistry.command.ServiceRegistryContract#organizationPrimaryAliasAdded
 */
@Event
public class OrganizationPrimaryAliasAdded extends OrganizationAliasAdded {

    @TargetAggregateIdentifier
    private final OrganizationId organizationId;
    private final String alias;

    public OrganizationPrimaryAliasAdded(
            OrganizationId organizationId,
            String alias
    ) {
        super(
            organizationId,
            alias
        );
        this.organizationId = organizationId;
        this.alias = alias;
    }

    public OrganizationId getOrganizationId() {
        return organizationId;
    }

    public String getAlias() {
        return alias;
    }

}

