// This code was generated by net.maritimecloud.common.cqrs.contract.SourceGenerator
// Generated Code is based on the contract defined in net.maritimecloud.serviceregistry.command.ServiceRegistryContract
// Please modify the contract instead of this file!
package net.maritimecloud.serviceregistry.command.api;

import org.axonframework.commandhandling.annotation.TargetAggregateIdentifier;
import net.maritimecloud.common.cqrs.contract.Event;
import net.maritimecloud.serviceregistry.command.organization.OrganizationId;

/**
 * GENERATED CLASS!
 * @see net.maritimecloud.serviceregistry.command.ServiceRegistryContract#organizationCreated
 */
@Event
public class OrganizationCreated {

    @TargetAggregateIdentifier
    private final OrganizationId organizationId;
    private final String primaryAlias;
    private final String name;
    private final String summary;
    private final String url;

    public OrganizationCreated(
            OrganizationId organizationId,
            String primaryAlias,
            String name,
            String summary,
            String url
    ) {
        this.organizationId = organizationId;
        this.primaryAlias = primaryAlias;
        this.name = name;
        this.summary = summary;
        this.url = url;
    }

    public OrganizationId getOrganizationId() {
        return organizationId;
    }

    public String getPrimaryAlias() {
        return primaryAlias;
    }

    public String getName() {
        return name;
    }

    public String getSummary() {
        return summary;
    }

    public String getUrl() {
        return url;
    }

}

