// This code was generated by net.maritimecloud.cqrs.tool.SourceGenerator
// Generated Code is based on the contract defined in net.maritimecloud.serviceregistry.command.ServiceRegistryContract
// Please modify the contract instead of this file!
package net.maritimecloud.serviceregistry.command.api;

import org.axonframework.commandhandling.annotation.TargetAggregateIdentifier;
import net.maritimecloud.cqrs.tool.Event;
import net.maritimecloud.serviceregistry.command.organization.OrganizationId;
import net.maritimecloud.serviceregistry.command.servicespecification.ServiceSpecificationId;
import net.maritimecloud.serviceregistry.command.servicespecification.ServiceType;

/**
 * GENERATED CLASS!
 * @see net.maritimecloud.serviceregistry.command.ServiceRegistryContract#serviceSpecificationCreated
 */
@Event
public class ServiceSpecificationCreated {

    @TargetAggregateIdentifier
    private final OrganizationId ownerId;
    private final ServiceSpecificationId serviceSpecificationId;
    private final ServiceType serviceType;
    private final String name;
    private final String summary;

    public ServiceSpecificationCreated(
            OrganizationId ownerId,
            ServiceSpecificationId serviceSpecificationId,
            ServiceType serviceType,
            String name,
            String summary
    ) {
        this.ownerId = ownerId;
        this.serviceSpecificationId = serviceSpecificationId;
        this.serviceType = serviceType;
        this.name = name;
        this.summary = summary;
    }

    public OrganizationId getOwnerId() {
        return ownerId;
    }

    public ServiceSpecificationId getServiceSpecificationId() {
        return serviceSpecificationId;
    }

    public ServiceType getServiceType() {
        return serviceType;
    }

    public String getName() {
        return name;
    }

    public String getSummary() {
        return summary;
    }

}

