// This code was generated by net.maritimecloud.cqrs.tool.SourceGenerator
// Generated Code is based on the contract defined in net.maritimecloud.serviceregistry.command.ServiceRegistryContract
// Please modify the contract instead of this file!
package net.maritimecloud.serviceregistry.command.api;

import org.axonframework.commandhandling.annotation.TargetAggregateIdentifier;
import net.maritimecloud.cqrs.tool.Event;
import net.maritimecloud.serviceregistry.command.organization.OrganizationId;
import net.maritimecloud.serviceregistry.command.servicespecification.ServiceSpecificationId;
import net.maritimecloud.serviceregistry.command.serviceinstance.ServiceInstanceId;
import net.maritimecloud.serviceregistry.command.serviceinstance.Coverage;
import net.maritimecloud.serviceregistry.command.servicespecification.ServiceType;

/**
 * GENERATED CLASS!
 * @see net.maritimecloud.serviceregistry.command.ServiceRegistryContract#serviceInstanceCreated
 */
@Event
public class ServiceInstanceCreated {

    @TargetAggregateIdentifier
    private final OrganizationId providerId;
    private final ServiceSpecificationId specificationId;
    private final ServiceInstanceId serviceInstanceId;
    private final String name;
    private final String summary;
    private final Coverage coverage;
    private final ServiceType serviceType;

    public ServiceInstanceCreated(
            OrganizationId providerId,
            ServiceSpecificationId specificationId,
            ServiceInstanceId serviceInstanceId,
            String name,
            String summary,
            Coverage coverage,
            ServiceType serviceType
    ) {
        this.providerId = providerId;
        this.specificationId = specificationId;
        this.serviceInstanceId = serviceInstanceId;
        this.name = name;
        this.summary = summary;
        this.coverage = coverage;
        this.serviceType = serviceType;
    }

    public OrganizationId getProviderId() {
        return providerId;
    }

    public ServiceSpecificationId getSpecificationId() {
        return specificationId;
    }

    public ServiceInstanceId getServiceInstanceId() {
        return serviceInstanceId;
    }

    public String getName() {
        return name;
    }

    public String getSummary() {
        return summary;
    }

    public Coverage getCoverage() {
        return coverage;
    }

    public ServiceType getServiceType() {
        return serviceType;
    }

}

