// This code was generated by net.maritimecloud.common.cqrs.contract.SourceGenerator
// Generated Code is based on the contract defined in net.maritimecloud.serviceregistry.command.ServiceRegistryContract
// Please modify the contract instead of this file!
package net.maritimecloud.serviceregistry.command.api;

import org.axonframework.commandhandling.annotation.TargetAggregateIdentifier;
import net.maritimecloud.common.cqrs.contract.Event;
import net.maritimecloud.serviceregistry.command.servicespecification.ServiceSpecificationId;

/**
 * GENERATED CLASS!
 * @see net.maritimecloud.serviceregistry.command.ServiceRegistryContract#serviceSpecificationNameAndSummaryChanged
 */
@Event
public class ServiceSpecificationNameAndSummaryChanged {

    @TargetAggregateIdentifier
    private final ServiceSpecificationId serviceSpecificationId;
    private final String name;
    private final String summary;

    public ServiceSpecificationNameAndSummaryChanged(
            ServiceSpecificationId serviceSpecificationId,
            String name,
            String summary
    ) {
        this.serviceSpecificationId = serviceSpecificationId;
        this.name = name;
        this.summary = summary;
    }

    public ServiceSpecificationId getServiceSpecificationId() {
        return serviceSpecificationId;
    }

    public String getName() {
        return name;
    }

    public String getSummary() {
        return summary;
    }

}

