// This code was generated by net.maritimecloud.cqrs.tool.SourceGenerator
// Generated Code is based on the contract defined in net.maritimecloud.serviceregistry.command.ServiceRegistryContract
// Please modify the contract instead of this file!
package net.maritimecloud.serviceregistry.command.api;

import org.axonframework.commandhandling.annotation.TargetAggregateIdentifier;
import net.maritimecloud.cqrs.tool.Event;
import net.maritimecloud.serviceregistry.command.serviceinstance.ServiceInstanceId;

/**
 * GENERATED CLASS!
 * @see net.maritimecloud.serviceregistry.command.ServiceRegistryContract#serviceInstanceAliasAdded
 */
@Event
public class ServiceInstanceAliasAdded {

    @TargetAggregateIdentifier
    private final ServiceInstanceId serviceInstanceId;
    private final String alias;

    public ServiceInstanceAliasAdded(
            ServiceInstanceId serviceInstanceId,
            String alias
    ) {
        this.serviceInstanceId = serviceInstanceId;
        this.alias = alias;
    }

    public ServiceInstanceId getServiceInstanceId() {
        return serviceInstanceId;
    }

    public String getAlias() {
        return alias;
    }

}

