// This code was generated by net.maritimecloud.common.cqrs.contract.SourceGenerator
// Generated Code is based on the contract defined in net.maritimecloud.serviceregistry.command.ServiceRegistryContract
// Please modify the contract instead of this file!
package net.maritimecloud.serviceregistry.command.api;

import org.axonframework.commandhandling.annotation.TargetAggregateIdentifier;
import net.maritimecloud.common.cqrs.contract.Event;
import net.maritimecloud.serviceregistry.command.organization.membership.MembershipId;
import net.maritimecloud.serviceregistry.command.organization.OrganizationId;

/**
 * GENERATED CLASS!
 * @see net.maritimecloud.serviceregistry.command.ServiceRegistryContract#userAppliedForMembershipToOrganization
 */
@Event
public class UserAppliedForMembershipToOrganization {

    @TargetAggregateIdentifier
    private final MembershipId membershipId;
    private final OrganizationId organizationId;
    private final String username;
    private final String applicationMessage;

    public UserAppliedForMembershipToOrganization(
            MembershipId membershipId,
            OrganizationId organizationId,
            String username,
            String applicationMessage
    ) {
        this.membershipId = membershipId;
        this.organizationId = organizationId;
        this.username = username;
        this.applicationMessage = applicationMessage;
    }

    public MembershipId getMembershipId() {
        return membershipId;
    }

    public OrganizationId getOrganizationId() {
        return organizationId;
    }

    public String getUsername() {
        return username;
    }

    public String getApplicationMessage() {
        return applicationMessage;
    }

}

